### ISSUE TITLE
Add support for accents

### ISSUE THREAD

**Issue by beapi-agency** [FacetWP/facetwp-alpha#3]
Hi,

I've found a bug with foreign chars. With English no problem but for example with "Ö" I get :

```
| A      |
| B      |
| C      |
| D      |
| E      |
| F      |
| G      |
| H      |
| I      |
| J      |
| K      |
| L      |
| M      |
| N      |
| Ö      |
| P      |
| R      |
| S      |
| T      |
| U      |
| W      |
| Y      |
```

with your SQL 

        $sql = "
        SELECT DISTINCT UPPER(LEFT(facet_display_value, 1)) AS letter
        FROM {$wpdb->prefix}facetwp_index
        WHERE facet_name = '{$facet['name']}' $where_clause
        ORDER BY letter";
        $results = $wpdb->get_col( $sql );

so the var $match is always false. Can you do something to fix it ?

Kind regards,
Julien.

**Comment by beapi-agency** [comment]
https://github.com/FacetWP/facetwp-alpha/blob/master/index.php#L71 the line where all the thing is done ^^

**Comment by TweetPressFr** [comment]
I made a PR to allow this https://github.com/FacetWP/facetwp-alpha/pull/4, can you check this ?

**Comment by mgibbs189** [comment]
@TweetPressFr Thanks for the PR. I don't think this fixes the underlying issue though.

See https://github.com/FacetWP/facetwp-alpha/blob/master/index.php#L108

Even though the letter will **appear** as active, when users click on it it's possible that they'll get no results. The query itself would still look for "O", instead of ["O" or "Ö"].

**Comment by TweetPressFr** [comment]
Hi, in my experience this is not the case, results are perfectly indexed in database and I get results at ?fwp_alphabet_exposant=O

**Comment by mgibbs189** [comment]
When you select "O" from the facet, do results starting with "Ö" appear in the list?

**Comment by TweetPressFr** [comment]
However I understand what you are saying, is that possible that some filters are applied somewhere to make "ö" appear as "o" in facetwp_index (database) ? some kinda of slug.

**Comment by TweetPressFr** [comment]
yes they appear in list.

**Comment by TweetPressFr** [comment]
actually @mgibbs189 a simple request such as :
`
SELECT * FROM `wp_facetwp_index` WHERE `facet_display_value` LIKE '%O%' `

and I get my results that start with  "Ö" in wp_facetwp_index seems accent Insensitive. 
Is it due to the db table collation ?

**Comment by beapi-agency** [comment]
@mgibbs189 I have some time I will look into this deeper cause it's a huge need.

**Comment by TweetPressFr** [comment]
<img width="636" alt="capture d ecran 2018-03-16 a 21 35 20" src="https://user-images.githubusercontent.com/6878027/37543686-a8feaefc-2962-11e8-8040-104133b28d1d.png">
<img width="747" alt="capture d ecran 2018-03-16 a 21 35 28" src="https://user-images.githubusercontent.com/6878027/37543687-a921b898-2962-11e8-82eb-bbd28520dbfc.png">
<img width="664" alt="capture d ecran 2018-03-16 a 21 35 36" src="https://user-images.githubusercontent.com/6878027/37543688-a944e6e2-2962-11e8-86cd-febcbff8d9ec.png">

there is no doubt that this is working fine to me but I've tested it with a fresh install, latest version of facetwp too. See pictures @mgibbs189

**Comment by mgibbs189** [comment]
@TweetPressFr @beapi-agency cool, thanks for confirming!
